language: go
go:
  - "1.13.x"
arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
install: skip
services:
  - docker
script:
  - docker login -u="flacatus" -p="n0KB1Z+36Jl/FjmyKtru9d3YtkfS5y9qSzhUP0xadlAYTtwDePiyXfAdhW05LQfB" quay.io
  - docker build -t quay.io/flacatus/che-operator:latest .
  - docker push quay.io/flacatus/che-operator:latest
